### PR TITLE
v3.1.0

### PR DESCRIPTION
**Pull request by felangel**
## Status
**READY**

## Breaking Changes
NO

## Description
- Update Hydrated Bloc to persist `initialState` upon initialization.
- Update to latest `effective_dart`.
- Add `synchronous` to prevent file corruption
- Refactor `HydratedBlocStorage.getInstance` to avoid using a singleton
- Upgrade to `path_provider: ^1.6.5` for MacOS support
- Invoke `onError` and continue emitting states when exceptions occur

## Todos
- [X] Tests
- [X] Documentation
- [X] Examples

## Impact to Remaining Code Base
- Non-Breaking changes which will be included in v3.1.0

### CODE REVIEW

**Comment by felangel** [comment]
@orsenkucher, @jorgecoca can you please take a look?

**Comment by felangel** [comment]
> It is also known as `synchronized` in the mass market @felangel

What do you mean?

**Comment by felangel** [comment]
> Won't it call delegate.onError second time? Considering bloc: 4.0.0-dev.3 changes @felangel

Yes but I’m planning on removing them when we upgrade to 4.0.0-dev.3. This is just an intermediate step.

**Comment by felangel** [comment]
> And I highly suggest putting some kind of error exposition
> like this
> 
> ```dart
> @override
> void onError(Bloc bloc, Object error, StackTrace stacktrace) {
>   super.onError(bloc, error, stacktrace);
>   assert(
>     false,
>     'Your $bloc has some problems with `toJson`ification, '
>     'hence you have a problem too🥳',
>   );
> }
> ```

I think this is a larger issue and I would like to address it at the bloc level rather than handle it specifically in hydrated bloc.

**Comment by orsenkucher** [comment]
> > It is also known as `synchronized` in the mass market @felangel
> 
> What do you mean?

Package is just called differently))

**Comment by orsenkucher** [comment]
> I think this is a larger issue and I would like to address it at the bloc level rather than handle it specifically in hydrated bloc.

This is pleasant to hear! It is quite hard to detect problems now

**Comment by felangel** [comment]
> > > It is also known as `synchronized` in the mass market @felangel
> > 
> > 
> > What do you mean?
> 
> Package is just called differently))

If you're referring to the meta commit that was independent of `synchronized` and we had to explicitly add `meta` as a dependency.

**Review by orsenkucher — DISMISSED** [review]
Now everything is consistent👍💯

**Pull request merged**
