### PR TITLE
v4.0.0

### LINKED ISSUE #48: Upgrade to bloc ^4.0.0
Hello
Do you have any plans on upgrading bloc package to the new released version?

### PR DESCRIPTION
**Pull request by felangel**
## Status
**READY**

## Breaking Changes
YES

## Description
- Upgrade to `bloc: ^4.0.0` and `flutter_bloc: ^4.0.0`
- onTransition moved from `HydratedBlocDelegate` to `HydratedBloc`

## Todos
- [X] Tests
- [X] Documentation
- [X] Examples

### CODE REVIEW

**Comment by kofan** [comment]
Hey, @felangel, how far is it from being released?
Thank you!

**Comment by felangel** [comment]
@kofan hopefully by next week. Still need to update the tests and there are additional changes that will potentially go into 4.0.0 which are currently in progress.

**Comment by kofan** [comment]
Great! Thank you, @felangel, for all your efforts and the amazing bloc library!

**Review by orsenkucher — DISMISSED** [review]
Should we mention `onTransition` was moved to bloc? Might surprise somebody))
Other things 👍👍

**Pull request merged**
