### PR TITLE
Web support

### PR DESCRIPTION
**Pull request by rodydavis**
## Status
READY

## Breaking Changes
NO

## Description
Support for Hydrated Bloc on the Web via html.window.localStorage

Survives browser restarts!

## Related PRs
N/A

## Todos
- [X] Tests
- [ ] Documentation
- [X] Examples

## Steps to Test or Reproduce
Outline the steps to test or reproduce the PR here.

```
flutter run -d chrome
```

## Impact to Remaining Code Base
This PR will affect:

* Support for Flutter Web

### CODE REVIEW

**Comment by felangel** [comment]
Hey @AppleEducate 👋 
Thanks for the contribution once again!

I'm starting to realize that it's probably not a great idea to handle all of the platforms at the `hydrated_bloc` layer and instead it would be much better to move these improvements into the lower level plugins like `path_provider` etc...

If we did that, then `hydrated_bloc` wouldn't need to change and it would also benefit many other packages which depend on the low-level plugins.

Thoughts?

**Comment by rodydavis** [comment]
Yeah I already have some PRs I’m working on for path_provider but it will be a bit till they land. If you want to release this as a -pre appended to the version it could be for those that want to test the web support until then. 👍🏼

**Comment by rodydavis** [comment]
But I agree, the lower the better

**Comment by felangel** [comment]
Thoughts on moving this to a web branch? That way people can try it out without needing to merge the code into master. Also, if you need help with the lower level packages lmk and I'm happy to help 👍

**Comment by rodydavis** [comment]
Ok Awesome! And I think that is a great option! create the branch and ill modify the pull request

**Comment by felangel** [comment]
> Ok Awesome! And I think that is a great option! create the branch and ill modify the pull request

Done ✅

**Comment by rodydavis** [comment]
Awesome! Change the PR pointer!

**Review by felangel — APPROVED** [review]
Thanks! 💯

**Comment by rodydavis** [comment]
Absolutely! :)

**Pull request merged**
